### PR TITLE
Fix CTC matching for emtpy frames

### LINKED ISSUE #138: CTC matcher fails if some frame of the predictions does not contain any objects
* traccuracy version: current `main`

# Description

I'm running into an edge case that makes the CTC matcher fail.
I have predictions where in some frame `t`, there is no objects, despite there being some objects in the corresponding frame of the ground truth. The matcher calls `TrackingGraph.nodes_by_frame[t]` on the prediction TrackingGraph, which throws a KeyError.

# Possible solutions
1) Return an empty list if there is no entry in for frame t in `nodes_by_frame`, or
2) Change type of `TrackingGraph.nodes_by_frame` to `collections.defaultdict(list)`.

I think I prefer 2), since it gets rid of the problem at the source. Let's discuss and I'll make a corresponding PR.

# Minimal example to reproduce the bug

These are the first cells of the repo's example notebook, with some additional lines that get rid of all predictions in frame 0.
```python
import os
from pathlib import Path
import pprint
import urllib.request
import zipfile

from tqdm import tqdm

from traccuracy import run_metrics
from traccuracy.loaders import load_ctc_data
from traccuracy.matchers import CTCMatcher, IOUMatcher
from traccuracy.metrics import CTCMetrics, DivisionMetrics

pp = pprint.PrettyPrinter(indent=4)


url = "http://data.celltrackingchallenge.net/training-datasets/Fluo-N2DL-HeLa.zip"
data_dir = 'downloads'

if not os.path.exists(data_dir):
    os.mkdir(data_dir)

filename = url.split('/')[-1]
file_path = os.path.join(data_dir, filename)
ds_name = filename.split('.')[0]


# Add a utility to make a progress bar when downloading the file
class DownloadProgressBar(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None:
            self.total = tsize
        self.update(b * bsize - self.n)

if not os.path.exists(file_path):
    print(f"Downloading {ds_name} data from the CTC website")
    # Downloading data
    with DownloadProgressBar(unit='B', unit_scale=True,
                             miniters=1, desc=url.split('/')[-1]) as t:
        urllib.request.urlretrieve(url, file_path, reporthook=t.update_to)
    # Unzip the data
    # TODO add a progress bar to zip as well
    with zipfile.ZipFile(file_path, 'r') as zip_ref:
        zip_ref.extractall(data_dir)

# remove detections in one frame of results
import pandas as pd
import tifffile
df = pd.read_csv("sample-data/Fluo-N2DL-HeLa/01_RES/res_track.txt", sep=" ", header=None)
s = df.iloc[:, 1]
df.iloc[:, 1] = s.replace(0, 1)
# print(df)
df.to_csv("sample-data/Fluo-N2DL-HeLa/01_RES/res_track.txt", sep=" ", header=False, index=False)
# df = pd.read_csv("res_track.txt", sep=" ", header=None)
# print(df)

mask0 = tifffile.imread("sample-data/Fluo-N2DL-HeLa/01_RES/mask000.tif")
empty = np.zeros_like(mask0)
tifffile.imwrite("sample-data/Fluo-N2DL-HeLa/01_RES/mask000.tif", empty)



gt_data = load_ctc_data(
    'downloads/Fluo-N2DL-HeLa/01_GT/TRA',
    'downloads/Fluo-N2DL-HeLa/01_GT/TRA/man_track.txt',
    name='Hela-01_GT'
)
pred_data = load_ctc_data(
    'sample-data/Fluo-N2DL-HeLa/01_RES', 
    'sample-data/Fluo-N2DL-HeLa/01_RES/res_track.txt',
    name='Hela-01_RES'
)

ctc_results = run_metrics(
    gt_data=gt_data, 
    pred_data=pred_data, 
    matcher=CTCMatcher(), 
    metrics=[CTCMetrics(), DivisionMetrics(max_frame_buffer=2)],
)
pp.pprint(ctc_results)
```

and here is the error:

```python
Matching frames:   0%|                                                                                                                                                                         | 0/92 [00:00<?, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[27], line 1
----> 1 ctc_results = run_metrics(
      2     gt_data=gt_data, 
      3     pred_data=pred_data, 
      4     matcher=CTCMatcher(), 
      5     metrics=[CTCMetrics(), DivisionMetrics(max_frame_buffer=2)],
      6 )
      7 pp.pprint(ctc_results)

File ~/code/traccuracy/src/traccuracy/_run_metrics.py:40, in run_metrics(gt_data, pred_data, matcher, metrics)
     37 if not all(isinstance(m, Metric) for m in metrics):
     38     raise TypeError("metrics must be a list of instantiated Metric objects")
---> 40 matched = matcher.compute_mapping(gt_data, pred_data)
     41 results = []
     42 for _metric in metrics:

File ~/code/traccuracy/src/traccuracy/matchers/_base.py:45, in Matcher.compute_mapping(self, gt_graph, pred_graph)
     40     raise ValueError(
     41         "Input data must be a TrackingData object with a graph and segmentations"
     42     )
     44 # Copy graphs to avoid possible changes to graphs while computing mapping
---> 45 matched = self._compute_mapping(
     46     copy.deepcopy(gt_graph), copy.deepcopy(pred_graph)
     47 )
     49 # Record matcher info on Matched object
     50 matched.matcher_info = self.info

File ~/code/traccuracy/src/traccuracy/matchers/_ctc.py:66, in CTCMatcher._compute_mapping(self, gt_graph, pred_graph)
     64 pred_frame = mask_pred[i]
     65 gt_frame_nodes = gt.nodes_by_frame[t]
---> 66 pred_frame_nodes = pred.nodes_by_frame[t]
     68 # get the labels for this frame
     69 gt_labels = dict(
     70     filter(
     71         lambda item: item[0] in gt_frame_nodes,
     72         nx.get_node_attributes(G_gt.graph, gt_label_key).items(),
     73     )
     74 )

KeyError: 0
```

# Severity
- Annoying, but still functional

### PR DESCRIPTION
**Pull request by bentaculum**
# Proposed Change
Fixes #138.

# Types of Changes
What types of changes does your code introduce? Put an x in the boxes that apply.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature or enhancement
- [ ] Documentation update
- [ ] Tests and benchmarks
- [ ] Maintenance (e.g. dependencies, CI, releases, etc.)

Which topics does your change affect? Put an x in the boxes that apply.
- [ ] Loaders
- [x] Matchers
- [ ] Track Errors
- [ ] Metrics
- [x] Core functionality (e.g. `TrackingGraph`, `run_metrics`, `cli`, etc.)

# Checklist
Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read the developer/contributing docs.
- [ ] I have added tests that prove that my feature works in various situations or tests the bugfix (if appropriate).
- [ ] I have checked that I maintained or improved code coverage.
- [x] I have checked the benchmarking action to verify that my changes did not adversely affect performance.
- [ ] I have written docstrings and checked that they render correctly in the Read The Docs build (created after the PR is opened).
- [ ] I have updated the general documentation including Metric descriptions and example notebooks if necessary.

### CODE REVIEW

**Comment by bentaculum** [comment]
Just noticed, the tests for the CTCMatcher are a bit minimalistic in general, it wouldn't hurt to add a test for the CTCMatcher that uses a non-equal GT and prediction.

**Review by DragaDoncila — COMMENTED** [review]
@bentaculum code looks fine to me but it would be good while we're here to add explicit testing for this: in `test_tracking_graph` just for constructing a graph and accessing `nodes_by_frame` of an empty frame, and also for `get_labels_with_overlap` by passing in empty frames. I know we need more tests for the overlap code and the CTC matchers anyway, but this would at least block regressions down the line.

**Comment by cmalinmayor** [comment]
@DragaDoncila @bentaculum I added the suggested tests. I also removed the unusued `TrackingGraph.get_nodes_in_frame()` function in favor of the implemented defaultdict approach. I believe the failing tests are due to the pandas dependency issue and not the actual tests (since they run locally) but I will have to fix that and merge to be sure.

**Comment by bentaculum** [comment]
Awesome, thanks :)

**Review by DragaDoncila — APPROVED** [review]
Looks great, thanks @cmalinmayor for adding those tests

**Pull request merged**
